version: "3"

services:
  library-api:
    restart: unless-stopped
    image: library-api-image
    container_name: library-api
    build:
      context: ./library
      dockerfile: Dockerfile

    ports:
      - "5000:5000"

  library-app:
    image: library-app
    container_name: library-app
    build:
      context: ./library-app
      dockerfile: Dockerfile

    ports:
      - "5001:80"
